study_name: Optimize_Template
trials: 20
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

pruner:
  name: pruner.PFLPruner
  kwargs:
    n_startup_trials: 10
    n_warmup_epochs: 10
    top_k: 10
    target_epoch: 50

search_space:
  net_config:
    nodes:
      type: categorical
      choices: [32, 64, 128]
    layers:
      type: int
      min: 3
      max: 5
  optimizer_config:
    lr:
      type: float
      min: 1.e-3
      max: 1.e-2
      log: true
  scheduler_config:
    upper_bound:
      type: int
      min: 300
      max: 400
      step: 50
    infimum_lr:
      type: float
      min: 1.e-7
      max: 1.e-4
      log: true
